### ISSUE TITLE
Gate Synthesis Accuracy 

### ISSUE THREAD

**Issue by zain2864** [isi-usc-edu/pyLIQTR#19]
There is an issue with the gate synthesis accuracy, in which, depending on the precision, it decomposes some rotations to be the identity gate. Here is an example to reproduce the results. In the Magnetic Lattices notebook ([Link](https://github.com/lanl-ansi/qc-applications/blob/main/notebooks/MagneticLattices.ipynb)), for the triangular lattice trotter implementation, under the Estimates section, when the energy precision is set to 1e-16, many rotations are turned into identity gates. These results can be seen from running the notebook and looking at the _triangle_trotter_re.json_ and _Trotter_Unitary.cpt.qasm_ files created. The path to see the files generated is: `notebooks/Trotter/triangle_circuits`

**Comment by rroodll** [comment]
Not a problem. Issue was sorted with filer via email exchange
