### ISSUE TITLE
New lattice implementation

### ISSUE THREAD

**Issue by jsmarsha11** [isi-usc-edu/pyLIQTR#23]
We would like to implement a variation of the Fermi Hubbard model that is currently included in pyLIQTR. In particular, we have a 2D square lattice, which also has 'diagonal' edges. For example, if we label the four vertices on a unit cell {0,1,2,3}, there are 6 edges: (0,1), (1,2), (2,3), (0,3), (0,2), (1, 3).

We have two coupling types within this lattice, which controls the hopping (where each site can have spin up and down): the regular square lattice has couplings $t$, and the diagonals have another coupling, $t^\prime$.
And we also have the density term on each site, of the form: $J n_\uparrow n_\downarrow$ (up/down occupation with strength $J$).

Is it possible for someone in the team to implement this? I discussed this at the recent QB meeting with Kaitlyn and Kevin. I don't think it makes sense for me to implement this, as we have a very lengthy approval process for public code releases.
Thanks!
Jeff Marshall (NASA Ames)

**Comment by rroodll** [comment]
This is currently under development, release date is pending.

**Comment by rroodll** [comment]
Fixed in v1.3.2 available on PYPI 11/8/2024
