### ISSUE TITLE
Circuits with no rotation gates

### ISSUE THREAD

**Issue by akataba** [isi-usc-edu/pyLIQTR#4]
While pyLIQTR is calculating gate precision it assumes rotation gates are always in the circuit. This is a problem since if there are no rotation gates one gets an error related to dividing by zero. This error is encountered when calling the method `clifford_plus_t_direct_transform` from `pyLIQTR.gate_decomp.cirq_transforms`

**Comment by rroodll** [comment]
Fixed in version 1.0.0
