### ISSUE TITLE
Certain Gate operations do not have an implemented _qasm_ method

### ISSUE THREAD

**Issue by tyleratrigetti** [isi-usc-edu/pyLIQTR#6]
Possibly related to https://github.com/isi-usc-edu/pyLIQTR/issues/5

When running the notebook `Examples/ApplicationInstances/FermiHubbard/fermi_hubbard-dynamics-qubitized.ipynb`, if one removes the lines:

```    
if ctr > 100:
        break
```
from the cell in section 4.2 that prints to QASM, one gets the error:

```
TypeError: object of type '<class 'cirq.ops.gate_operation.GateOperation'>' does have a _qasm_ method, but it returned NotImplemented or None.
```
Error occurs on system with the following specs:
Python 3.9.10
OS: macOS 14.2.1
Chip: Apple M1 Max
pyLIQTR version 1.0.0

**Comment by rroodll** [comment]
This has been addressed in #5, closing as duplicate.
