### ISSUE TITLE
[Examples] Workflow Flowchart won't display/is missing in _Angle_Generation_Overview.ipynb

### ISSUE THREAD

**Issue by olgOk** [isi-usc-edu/pyLIQTR#7]
Hi!

While browsing the examples, I have noticed that the [_Angle_Generation_Overview.ipynb](https://github.com/isi-usc-edu/pyLIQTR/blob/main/Examples/AngleGeneration/_Angle_Generation_Overview.ipynb) is missing a work flow flowchart. It seems that the path to the image may be broken. The screenshot is attached below.

![Screenshot 2024-03-11 at 5 28 42 PM](https://github.com/isi-usc-edu/pyLIQTR/assets/46659064/8620fb57-dc34-46aa-80bf-69ea8933d11b)

Thank you!

**Comment by rroodll** [comment]
Will be fixed in the post 1.3.0 release. I don't have the version number just yet.

**Comment by rroodll** [comment]
fixed in version 1.3.1 and available on [pypi](https://pypi.org/project/pyLIQTR/)
