### ISSUE TITLE
Cannot compare prepare operation to Ry operation

### ISSUE THREAD

**Issue by tyleratrigetti** [isi-usc-edu/pyLIQTR#9]
I know this seems like a silly thing to do, but it comes up when I'm analyzing circuits and I want to know if I've seen another operation before. It looks like the `prepare` operation doesn't allow comparison to other `cirq` operations, such as `Ry`.

Minimal code to reproduce:

`pyLIQTR` 1.1.1
`python` 3.9.10

```
import pyLIQTR.circuits.operators.prepare as prep
import cirq
qbs = [cirq.LineQubit(i) for i in range(2)]
alphas = [.1,.2,.3,.4]
op1 = prep.Prepare(qbs,alphas).on(*qbs)
op2 = cirq.Ry(rads=0.1).on(qbs[0])
op1 == op2
```

Error returned is 
`AttributeError: 'Ry' object has no attribute 'total_decomp'`

I believe this is happening because the `prepare` gate refines the `__eq__` method in a way that requires `Ry` to have a `total_decomp` method, which it does not. Nor do other native `cirq` gates I assume.

**Comment by rroodll** [comment]
Fixed and merged in https://github.com/isi-usc-edu/pyLIQTR/pull/10
